name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Configure custom server
      env:
        NTFY_APP_BASE_URL: ${{ secrets.NTFY_APP_BASE_URL }}
        NTFY_FCM_CONFIG: ${{ secrets.NTFY_FCM_CONFIG }}
      run: |
        echo "Updating base URL"
        sed -i 's#\(<string name="app_base_url".*>\).\+\(</string>\)#\1${NTFY_APP_BASE_URL}\2#g' app/src/main/res/values/values.xml
        echo "Writing Firebase config to app/google-services.json"
        printf "${NTFY_FCM_CONFIG}" >> app/google-services.json

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew assemblePlayRelease

    - uses: actions/upload-artifact@v3
      with:
        name: Ntfy Android
        path: **/*.apk
