name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Configure custom server
      env:
        NTFY_APP_BASE_URL: ${{ secrets.NTFY_APP_BASE_URL }}
        NTFY_FCM_CONFIG: ${{ secrets.NTFY_FCM_CONFIG }}
      run: |
        echo "Updating base URL"
        echo "<todo>"
        echo "Writing Firebase config to app/google-services.json"
        echo "${NTFY_APP_BASE_URL}" >> app/google-services.json

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
